version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: crpt-service-database
    ports:
      - "5432:5432"